x1 = float(input('Digite a primeira nota: '))
x2 = float(input('Digite a segunda nota: '))
x3 = float(input('Digite a terceira nota: '))
x4 = float(input('Digite a quarta nota: '))
print('A média aritmética é',(x1+x2+x3+x4)/4)